---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: true
    - name: start nginx
      service:
          name: nginx
          state: started
          enabled: true
    - name: copy website
      copy:
        src: ../assets/index.html
        dest: /var/www/html/index.html
        mode: 0644
